version: "3"
services:
    dashboard:
        image: rmountjoy/dashmachine:latest
        volumes:
            - ../data/dashboard:/dashmachine/dashmachine/user_data
        ports:
            - "8002:5000"
        restart: unless-stopped
    cloud:
        image: nextcloud
        ports:
            - "8004:80"
        volumes:
            - ../data/cloud/html:/var/www/html
    
