version: "3"
services:
    db:
        image: mysql:latest
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        env_file: ../.env
        ports:
            - "3306:3306"
        volumes:
            - ../data/db:/var/lib/mysql
     nginx:
        image: jc21/nginx-proxy-manager:latest
        restart: unless-stopped
        ports:
          # Public HTTP Port:
          - '80:80'
          # Public HTTPS Port:
          - '443:443'
          # Admin Web Port:
          - '81:81'
        environment:
          # Uncomment this if IPv6 is not enabled on your host
          # DISABLE_IPV6: 'true'
        volumes:
          # Make sure this config.json file exists as per instructions above:
          - ../data/proxy/config:/app/config
          - ../data/proxy/data:/data
          - ../data/data/proxyletsencrypt:/etc/letsencrypt
    depends_on:
      - db
    cms:
        image: agentejo/cockpit
        ports:
            - 8003:80
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: unless-stopped
        ports:
            - 8081:80
    portainer:
        image: portainer/portainer:alpine
        command: -H unix:///var/run/docker.sock
        restart: unless-stopped
        ports:
            - 9000:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ../data/portainer:/data
