version: "3"
services:
    influxdb:
        container_name: influxdb
        image: influxdb:latest
        restart: unless-stopped
        ports:
            - 8083:8083
            - 8086:8086
        volumes:
            - ../data/influxdb:/var/lib/influxdb
    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        links:
            - influxdb
        ports:
            - 3000:3000
        depends_on:
            - influxdb
        volumes:
            - ../data/grafana:/var/lib/grafana
    dashboard:
        image: rmountjoy/dashmachine:latest
        volumes:
            - ../data/dashboard:/dashmachine/dashmachine/user_data
        ports:
            - "8002:5000"
        restart: unless-stopped
